# Workflow name
name: "Chromatic Deployment"

# Event for the workflow
on:
  push:
    branches:
      - master # run the job below when every branch merge to master branch

# List of jobs
jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      # see https://github.com/actions/checkout
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: npm install
        #👇 Adds Chromatic as a step in the workflow https://github.com/chromaui/action
      - uses: chromaui/action@v1
        # Options required for Chromatic's GitHub Action
        with:
          #👇 Chromatic projectToken, see https://storybook.js.org/tutorials/intro-to-storybook/react/en/deploy/ to obtain it
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
